export const DAILY_NOTIFICATION_PHRASES = [
  'No olvides que te amo',
  'Eres mi lugar favorito',
  'Estoy pensando en ti',
  'Tu sonrisa me alegra todo',
  'Gracias por existir',
  'Me encantas cada dia mas',
  'Eres mi persona favorita',
  'Ojala estes sonriendo',
  'Te mando un abrazo enorme',
  'Siempre estoy contigo',
  'Me haces muy feliz',
  'Eres mi estrella favorita',
  'Que descanses bonito',
  'Te amo con todo mi corazon',
  'Hoy tambien eres especial',
  'Me gusta quererte asi',
  'Eres magia en mi vida',
  'Nunca olvides lo valiosa que eres',
  'Mi dia mejora contigo',
  'Te elijo siempre',
  'Eres mi pensamiento mas bonito',
  'Cuenta conmigo siempre',
  'Me haces sentir en casa',
  'Te quiero cerquita siempre',
  'Espero ser tu compañero de vida',
  'Estoy orgulloso de ti',
  'Gracias por ser tu',
  'Te amo mas de lo que digo',
  'Eres mi alegria diaria',
  'Duerme sabiendo que te amo',
] as const;

